# Generated by Django 5.2.13 on 2026-05-08 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="auditor",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Auditor (Auditorium/Room)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="auditor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditor_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible User",
            ),
        ),
    ]
