# Generated by Django 5.2.13 on 2026-05-09 08:03

import django.db.models.deletion
from django.db import migrations, models


def nullify_asset_types(apps, schema_editor):
    """Сначала обнуляем все внешние ключи asset_type"""
    Asset = apps.get_model('assets', 'Asset')
    Asset.objects.update(asset_type=None)


def create_asset_types(apps, schema_editor):
    """Создание начальных типов активов"""
    AssetType = apps.get_model('assets', 'AssetType')
    
    initial_types = [
        {'name': 'Оборудование', 'code': 'hardware', 'description': 'Компьютерное и сетевое оборудование'},
        {'name': 'Программное обеспечение', 'code': 'software', 'description': 'Лицензии и программы'},
        {'name': 'Мебель', 'code': 'furniture', 'description': 'Офисная и учебная мебель'},
        {'name': 'Техника', 'code': 'equipment', 'description': 'Электронная техника и устройства'},
        {'name': 'Другое', 'code': 'other', 'description': 'Прочие активы'},
    ]
    
    for type_data in initial_types:
        AssetType.objects.create(**type_data)


def update_asset_types(apps, schema_editor):
    """Обновление существующих активов с привязкой к типам (по умолчанию 'other')"""
    Asset = apps.get_model('assets', 'Asset')
    AssetType = apps.get_model('assets', 'AssetType')
    
    # Устанавливаем 'other' для всех активов без типа
    other_type = AssetType.objects.filter(code='other').first()
    if other_type:
        Asset.objects.filter(asset_type__isnull=True).update(asset_type=other_type)


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_auditor_asset_auditor_user"),
    ]

    operations = [
        migrations.RunPython(nullify_asset_types, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название типа"
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Код типа")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Тип актива",
                "verbose_name_plural": "Типы активов",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(create_asset_types, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.assettype",
                verbose_name="Тип актива",
            ),
        ),
        migrations.RunPython(update_asset_types, reverse_code=migrations.RunPython.noop),
    ]
