# Generated by Django 5.2.13 on 2026-05-04 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        help_text="Type of export (assets, locations, transfers)",
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "filters",
                    models.JSONField(
                        blank=True, help_text="Filters applied", null=True
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        default=0, help_text="Number of records exported"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Log",
                "verbose_name_plural": "Export Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("scan", "QR Scan"),
                            ("export", "Export"),
                            ("transfer", "Transfer"),
                            ("checkout", "Checkout"),
                            ("checkin", "Checkin"),
                            ("report_damage", "Report Damage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, help_text="Changes made (old -> new)", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="reports_aud_user_id_109722_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="reports_aud_action_fb2039_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="reports_aud_model_n_dc47ea_idx",
                    ),
                ],
            },
        ),
    ]
