services:
  - type: web
    name: edudata-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn edudata.wsgi:application --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
        sync: false
      - key: SECRET_KEY
        generateValue: true
        sync: false
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1
        sync: false
      - key: DB_ENGINE
        value: django.db.backends.postgresql
        sync: false
      - key: DB_NAME
        fromService:
          type: postgres
          name: edudata-db
          property: databaseName
        sync: false
      - key: DB_USER
        fromService:
          type: postgres
          name: edudata-db
          property: user
        sync: false
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: edudata-db
          property: password
        sync: false
      - key: DB_HOST
        fromService:
          type: postgres
          name: edudata-db
          property: host
        sync: false
      - key: DB_PORT
        value: 5432
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
        fromService:
          type: frontend
          property: url
          prefix: https://
