# Generated by Django 5.2.13 on 2026-05-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Location Name"),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("floor", "Floor"),
                            ("room", "Room"),
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Location Type",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Building"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Floor"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Room Number"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contact Person",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(blank=True, null=True, verbose_name="Capacity"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_locations",
                        to="locations.location",
                        verbose_name="Parent Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
                "unique_together": {("parent_location", "name")},
            },
        ),
    ]
